### ISSUE TITLE
Clean github

### ISSUE THREAD

**Issue by mangalpranjal** [ariesiitr/Image-Emotion-Detection-and-Caption-Generator#1]
1. Remove irrelevant files
2. Elaborate README

**Comment by Kashish-Agrawal** [comment]
issues resolved

**Comment by mangalpranjal** [comment]
1. Proper formatting of github.
2. 
![image](https://user-images.githubusercontent.com/48639793/169639594-8e4911bf-5bff-470f-bcc8-3bd96c9546e9.png)
 Are these files important?
3. Add some basic comments in Jupyter Notebook.

**Comment by Kashish-Agrawal** [comment]
ok resolved.
